### ISSUE TITLE
Include Support for Windows

### ISSUE THREAD

**Issue by szahn** [NarrativeScience/log.io#102]
npm fails to install log.io on windows. Please provide support for Windows. I can provide the error logs from the install output if needed.

**Comment by ZaLiTHkA** [comment]
This is not a log.io issue.. Pretty sure it comes down to your Windows environment configuration directly affecting the install-time requirements of socket.io. @kadaan shared half the solution in his post above.

Make sure you have either MS Visual Studio 2010 or 2012 installed (no need to run it, just have it's build tools on your `%path%`, which is handled by it's own installer), then install with the following command:

    npm i -g log-io --msvs_version=2012

Naturally, if you have VS 2010 instead, use that for the version parameter.

For the record, I just installed this without any errors or warnings on my Win 8.1 x64 system.

**Comment by msmathers** [comment]
v0.4x uses npm's built-in "bin" scripts for process invocation and no longer requires root/sudo access.  It also uses the latest LTE version of node.js, and is likely to be a lot more compatible with most OSes.
