### ISSUE TITLE
Ubuntu daemonize script is not up to date

### ISSUE THREAD

**Issue by nvquanghuy** [NarrativeScience/log.io#106]
First, thanks for an awesome software and very clear installation guide. I managed to get it up and running within 10 minuntes.

1/ It took me a while to get log.io upstart to work. The main line of the upstart script is:

```
exec su -s /bin/sh -c 'exec "$0" "$@"' logio -- /usr/local/bin/log.io-server
```

There is no `logio` user if I follow the default installation guide. And it took me awhile to fully understand how it works. **I think the doc should add: Replace logio with your ubuntu user (e.g. ubuntu).**

2/ **For people who install NodeJS through nvm**, log.io is installed into `~/.nvm/<VERSION>`, to get it to work:

Make `~/.nvm/nvm-exec` from `https://gist.github.com/nvquanghuy/8034406`

Change the exec line to (remember to change NODE_VERSION and logio to your Ubuntu username)

```
exec su -s /bin/sh -c 'NODE_VERSION=0.10.20 exec "$0" "$@"' ubuntu -- /home/ubuntu/.nvm/nvm-exec log.io-server
```

All in all, thanks for an awesome piece of software.

**Comment by robert-irribarren** [comment]
This took me a few hours. My own solution is to run it via pm2 directly as a node application.
I hope this helps anyone!

pm2 start /usr/lib/node_modules/log.io/bin/log.io-harvester --name="logio-harvester"
pm2 start /usr/lib/node_modules/log.io/bin/log.io-server --name="logio-server"
