### ISSUE TITLE
Harvester service restart

### ISSUE THREAD

**Issue by mmornati** [NarrativeScience/log.io#114]
If I restart an harvester node is not shown anymore in the left column of the log.io server.
The only fix I found at the moment:
- restart the log.io server
- restart all (!!!!) harvester services...

With a big installation is not really simple to workaround this problem. Have you got any information for us?

**Comment by gilad905** [comment]
Although the terminology has changed, I can still reproduce this:

- installed the server on some machine.
- installed the file input on a separate machine. it properly connects to the server and visible in the web UI.
- stopped the server. the file input process doesn't print anything about it.
- restarted the server. server prints regular restart messages. tried also with "debug": true.
- still, the file input process doesn't print anything new. no input sources are shown in the web UI.
- waited a few minutes, no change.

Only after I restart the file input, everything works again.
