### ISSUE TITLE
[feature request] Allow the use of hashed passwords.

### ISSUE THREAD

**Issue by LaKing** [NarrativeScience/log.io#123]
To integrate log.io properly into my project, I would need authentication against a hashed password in the web_server.conf. 

lib/server.js line 367?

**Comment by msmathers** [comment]
v0.4x removes support for auth in the log.io server.  We currently recommend using an nginx reverse proxy to add authentication in front of the log.io server.  The following recipe seems to work for most people: https://stackoverflow.com/a/29232687
