### ISSUE TITLE
More nodes than configured

### ISSUE THREAD

**Issue by wirehack7** [NarrativeScience/log.io#130]
After a while it shows up more node counting than there are nodes.
I added 3 nodes, after a while in the footer it shows up more than 3 nodes, like 6, 4 etc.

What causes this behaviour?

New nodes are not shown in the node overview of the sidebar. Just the number in the footer increases.

**Comment by msmathers** [comment]
Try upgrading to v0.4x, it has completely new server & UI components that manage stream/node state differently.
