### ISSUE TITLE
JBoss logs reporting too early

### ISSUE THREAD

**Issue by rmontagud** [NarrativeScience/log.io#132]
I'm trying to get harvester transmit JBoss logs, but it seems either harvester reads logs too fast or jboss writes too often as seen on the following screenshot. 

![jboss](https://cloud.githubusercontent.com/assets/21723/4339163/7cca8baa-4020-11e4-99c9-7c1f6ee36dfa.JPG)

Is there a way to tell harvester to wait before sending log messages to server?

Current server setup is Node 0.10.29 on CentOS 6.5

**Comment by msmathers** [comment]
Try upgrading to log.io v0.4x, which is a complete rewrite of the harvester component.  It has new file parsing / message handling logic that may address this.
