### ISSUE TITLE
error: Invalid TCP message

### ISSUE THREAD

**Issue by MrAndrewWhite** [NarrativeScience/log.io#135]
Hi

Node: v.0.10.31
NPM: 2.1.4
Log.io: 0.3.4

I'm running into issues with log.io. I installed and am able to start the server and harvester but when I connect to log.io it looks like it doesn't understand the headers.

error: Invalid TCP message: GET / HTTP/1.1
error: Invalid TCP message: Host: localhost:28777
error: Invalid TCP message: Connection: keep-alive
error: Invalid TCP message: User-Agent: Mozilla/5.0 (X11; Linux armv6l) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.94 Safari/537.4
error: Invalid TCP message: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
error: Invalid TCP message: Accept-Encoding: gzip,deflate,sdch
error: Invalid TCP message: Accept-Language: en-US,en;q=0.8
error: Invalid TCP message: Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
error: Invalid TCP message: 
error: Lost TCP connection...

Have you seen this issue before?

**Comment by msmathers** [comment]
Yeah as @dimon222 pointed it it looks like the TCP server is receiving HTTP requests.  The server listens on two separate ports, one for TCP connections and the other for HTTP requests.  Either your harvester & server conf aren't aligned, or there's a proxy layer between the two that is misrouting traffic.

Also try upgrading to v0.4x, the entire harvester/server stack has been rewritten.
