### ISSUE TITLE
Not getting Realtime logs

### ISSUE THREAD

**Issue by bentech4u** [NarrativeScience/log.io#136]
HI

i am new to log.io. I have installed log.io as per the tutorial : http://www.tecmint.com/linux-server-log-monitoring-with-log-io/

i am getting the page . But the logs are not realtime. i need to wait a log to get displayed on the web page

the "elapsed" on the downside of the page is increasing. I tried with IE, firefox & chrome.

please help me to solve this.

regards,
Ben

**Comment by msmathers** [comment]
v0.4x is a complete rewrite of the harvester/server/ui stack.  Try upgrading to the latest version and try again.
