### ISSUE TITLE
Less seems too old

### ISSUE THREAD

**Issue by magicdawn** [NarrativeScience/log.io#138]
when i run `cake build`,error happened when run `lessc -o`,cause new version of less don't support `-o` option to specify output, problem likes #111 

less@1.3.3 was released in `'2012-12-30T09:43:43.761Z'`, and `util.puts` is deprecated in v0.11.x(only v0.11.13 tested)

would this project update the less version ?

**Comment by msmathers** [comment]
v0.4.3 has a fully rewritten UI that uses the latest version of SASS.
