### ISSUE TITLE
Cant use runit or supervisor to work with log.io

### ISSUE THREAD

**Issue by davidmontgom** [NarrativeScience/log.io#141]
Hi,

Why cant I use supervisod?  Below is how I start bue i get the below error.  I run on the command then the process works.

[program:io-server]
command = /usr/bin/node /usr/bin/log.io-server

process_name=%(program_name)s
autostart=true
autorestart=true
stopsignal=KILL
stopasgroup = true
killasgroup = true

stdout_logfile=/tmp/supervisor_io-server.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10

stderr_logfile = /tmp/supervisor_io-server.err
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10

user=ubuntu

[group:io-server_server]
programs=io-server

module.js:340
    throw err;
          ^
Error: Cannot find module 'undefined/.log.io/web_server.conf'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/log.io/bin/log.io-server:9:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

module.js:340
    throw err;

**Comment by Strangerxxx** [comment]
Same problem :+1:

**Comment by rachner** [comment]
The error occurs because the server tries to read the HOME environment variable. If it is not set, it cannot read the configuration file. I solved this by setting the HOME variable in my supervisor configuration to contain the location of the ".log.io" folder.

```
[program:io-server]
...
environment=HOME="/your/path/.log.io"
...
```

**Comment by msmathers** [comment]
The latest version of log.io (v0.4x) uses npm's built-in "bin" scripts to invoke the server/input processes and no longer requires root/sudo access.  It also supports using environment variables to point to a custom configuration path: `LOGIO_FILE_INPUT_CONFIG_PATH` and `LOGIO_SERVER_CONFIG_PATH`.
