### ISSUE TITLE
Doesn't seem to work behind reverse proxy (nginx)

### ISSUE THREAD

**Issue by ianbamforth** [NarrativeScience/log.io#142]
I've exposed port 28778 through nginx, but all I get is the basic web page - none of the log content is shown.  Any clues what ports / routes are required in order to make it work?

**Comment by denydias** [comment]
Works like a charm!

**Comment by bikashsharmabks** [comment]
Hello,

I am trying to put log.io behind nginx server (1.8 version)
I tries out the above config but I get no response. But I do below config for nginx I get error Cannot GET /logio/ 404

Here is my config

```
location  /logio/ {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass http://localhost:28778;

          # Socket.IO Support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
```

**Comment by hajimezhao** [comment]
Hi guys,
Do we have any update for this issue? I also need to server log.io behind nginx proxy. Thank you very much!

Cheers,
Khon

**Comment by strannik19** [comment]
@hajimezhao in first line, the location directive, you are missing the part for socket.io. the original example uses `location ~* /(logio|socket\.io)/`  to match both /logio paths (what you will be typing into the address bar) and /socket.io (the js talked to the server with this url prefix).
also, you need the rewrite rule to get rid of the logio prefix in the path when nginx fires off the requests to the logio web server running at http://127.0.0.1:28778:
`rewrite ^/logio/(.*) /$1 break;`
so it should look like this: 
```
location   ~* /(logio|socket\.io)/ {
          rewrite ^/logio/(.*) /$1 break;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass http://127.0.0.1:28778;

          # Socket.IO Support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
```

**Comment by msmathers** [comment]
Similar to the responses above, this nginx recipe seems to be the agreed-upon solution: https://stackoverflow.com/a/29232687
