### ISSUE TITLE
The connection to ws://logio.org:28778/socket.io/1/websocket/... was interrupted while the page was loading

### ISSUE THREAD

**Issue by mgprogm** [NarrativeScience/log.io#143]
I found error message in firefox console:
"The connection to ws://logio.org:28778/socket.io/1/websocket/vtd2inn1dw_Bi2RuEfa_ was interrupted while the page was loading.
this.websocket = new Socket(this.prepareUrl() + query);"

on version  0.3.4
How to fix it

**Comment by msmathers** [comment]
Try using the latest version of log.io, which drastically updates the version of socket.io being used.
