### ISSUE TITLE
Issues adding new node

### ISSUE THREAD

**Issue by devster31** [NarrativeScience/log.io#144]
Hi, I'm having issues adding a new node, this is my harvester.conf

```
exports.config = {
  nodeName: "nginx_node",
  logStreams: {
    nginx_access: [
      "/var/log/nginx/access.log"
    ],
    nginx_error: [
      "/var/log/nginx/error.log"
    ]
  }
  nodeName: "log.io_node",
  logStreams: {
    log.io_server: [
      "/var/log/upstart/log.io-server.log"
    ],
    log.io_harvester: [
      "/var/log/upstart/log.io-harvester.log"
    ]
  },
  server: {
    host: '0.0.0.0',
    port: 28777
  }
}
```

what am I missing?

**Comment by KevinJay** [comment]
I'm meeting the same problem, did you find a solution?

**Comment by hanneshal** [comment]
I don't think its possible to add nodes to the harvester. Every harvester IS defacto a node, because you are on the same machine(which is  node). You can only add new node streams.

regards

**Comment by KenanSulayman** [comment]
`nodeName`, as it is currently implemented, is a de-facto server descriptor. That is, you're limited to one nodeName per Server. However, you're free to implement a harvester yourself using the *Server TCP interface*.

Example:

1. Register a new node `appmonitor` with stream associations: `errors` and `registrations`, where `errors` is a stream of logged exceptions that happened in your app and `registrations` is a stream of new registrations that happen in your app.
2. Push respective events as you connect to the Server TCP interface.

Check out the [custom harvester](https://gist.github.com/KenanSulayman/f7e55a28df614c520576) (CS & JS) I just build for you as an example.

**Comment by berrywira** [comment]
I don't know this problem has solved or not yet.
But, when you want add new node. on configuration harvester :

Parameter server: [
    host : IP_Server,
    port : 28777,
}

and configuration log_server.conf

exports.config = {
  host: 'IP_Server'
  port: 28777
}

Now, I running log.io with no problem.

**Comment by msmathers** [comment]
v0.4.3 has a new configuration scheme which allows a single file input (formerly harvester) process to define multiple stream/source pairs.
