### ISSUE TITLE
Non-Ubuntu install instructions?

### ISSUE THREAD

**Issue by blobhouse** [NarrativeScience/log.io#146]
Hello,

I'm trying to install log.io on centos, and I've found that your install instructions seem to be ubuntu-specific.  In particular, this line:

`npm install -g log.io --user "ubuntu"`

fails with the equivalent of a "no such user" error. 

I would work around this myself, but I've also found that I cannot find any documentation for this --user flag.  Is it specific to log.io?  I'm just not sure if it means "install as this user," or "run as this user," or both, some other less obvious thing.  I'll keep playing with it, but I wanted to mention that this is a bit of an impediment.  FYI, and thanks.

**Comment by hanneshal** [comment]
I'm running log.io on centos, based upon this instructions:
http://www.tecmint.com/linux-server-log-monitoring-with-log-io/

Another working article:
https://github.com/Ennexa/logio-initscript

The --user param gets passed to the install script, log.io tries to run as this user. npm install -g will install this script in the global (systemwide) context for every user. 

regards

**Comment by msmathers** [comment]
v0.4.3 uses the more idiomatic npm `bin` script to invoke processes, and no longer requires root/sudo, so installation should be a lot more straightforward.  See the latest README for installation instructions.
