### ISSUE TITLE
Is Log.io still maintained?

### ISSUE THREAD

**Issue by hanneshal** [NarrativeScience/log.io#148]
Hey guys|girls at Narrative Science,

just a question. Is Log.io still supported or do you just don't have any time to answer / close the issues and accept / decline some of the PR's.

I love Log.io so I'm just curious.

regards from Germany

Johannes

**Comment by ws141** [comment]
I'm sorry to tell you but id say it's not afaik.
I'v had a pull request open for a quite a while now https://github.com/NarrativeScience/Log.io/pull/93

**Comment by w33zy** [comment]
Just my luck... just when I am discovering this

**Comment by yangwao** [comment]
I'm using Log.io as well, so let's review PR or give someone responsible access.
Thanks!

**Comment by emilsoman** [comment]
@ws141 Are there alternatives to log.io ?

**Comment by OhadR** [comment]
@emilsoman maybe elasticsearch? https://www.elastic.co/

**Comment by jfcabral** [comment]
Maybe https://github.com/HansHammel/Log.io.coffee ?

**Comment by ren-kun** [comment]
Coffee throws this error for me when I try to install it

contextify@0.1.15 install: `node-gyp rebuild`
exit status 1
Failed at the contextify@0.1.15 install script 'node-gyp rebuild

**Comment by lcrespilho** [comment]
ren-kun, i get the same error. Have o manage to install it? Tks.

**Comment by ren-kun** [comment]
Nope I havent,

Check this link here - https://github.com/HansHammel/Log.io.coffee/issues/1#issuecomment-268840926

I think its a dead project for sure, if any progress, it will be something with almost zero priority

**Comment by msmathers** [comment]
https://github.com/NarrativeScience/log.io/releases/tag/v0.4.3
