### ISSUE TITLE
Windows install log.io-server command not working

### ISSUE THREAD

**Issue by victw** [NarrativeScience/log.io#149]
This is probably the wrong place to post this.  I'm new to node.js and log.io looked like an interesting place to start.
I'm installing on a windows machine.  Not sure if that worked correctly.  When I try to run log.io-server I get "Windows can't open this file:"  Wrong command?  Wrong place? Wrong rights?
Any suggestions on where to learn more?

I tried to run from node_modules\log.io\bin

Thanks.

**Comment by ian9723** [comment]
Use "log.io-server.cmd" in windows.  Same .cmd deal for the harvester if you are using it.

**Comment by gravidThoughts** [comment]
Is this related to an implementation detail? 

Every other global node package with a command installed on my machine does not require adding the `.cmd`.

**Comment by msmathers** [comment]
v0.4.3 uses the more idiomatic npm `bin` script to invoke server & harvester process, and no longer requires root/sudo, so this issue should be resolved.
