### ISSUE TITLE
[Request Help] HTTP Authentication

### ISSUE THREAD

**Issue by Gh0styyy** [NarrativeScience/log.io#150]
Hi,

I found this a week ago, and to be honest I like it :)
How do I set up http authentication on it?

And would it be possible to have multiple users with multiple accounts?
As I am trying to use this to monitor certain things and if I need to revoke access to one user I would rather not have to change the login password every time.

Thanks in advanced, any help would be appreciated.

**Comment by tianchaijz** [comment]
A simple way, using Nginx as a reverse proxy, and then use its [basic authorization module](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html).

**Comment by msmathers** [comment]
As mentioned above, would recommend using an nginx reverse proxy configured to work with socket.io.  This recipe seems to work: https://stackoverflow.com/a/29232687
