### ISSUE TITLE
Ongoing maintenance and support; future of log.io

### ISSUE THREAD

**Issue by KenanSulayman** [NarrativeScience/Log.io#151]
Hey,

We're in the process of deploying this in large clusters for our server operators.

I'm a bit worried since Log.io didn't seem to get much engineering effort in the past. _That is, I'd be interested in helping maintain in case you lack time or simply lost interest in this matter._ Engineering will happen in within my paid work hours and thus be covered (_sponsored_) by our company.

Cheers

/cc @msmathers

**Comment by jsam** [comment]
I can help as well.

**Comment by KenanSulayman** [comment]
@jsam we're starting a derivative over at [log.io-ng](https://github.com/perint/log.io-ng), if you'd like to help, please create an issue that you would like to become a contributor and I will add you :-)

**Comment by ronaldbroens** [comment]
@KenanSulayman I see this project is not realy active anymore, what are your plans with  log.io-ng? - I will also message you at your fork-project page

**Comment by wufenglinux** [comment]
> @jsam我们在[log.io-ng](https://github.com/perint/log.io-ng)开始衍生，如果你想帮忙，请创建一个你想成为贡献者的问题，我会加你:-)

hello Are you still maintaining this project?

**Comment by wufenglinux** [comment]
> @jsam we're starting a derivative over at [log.io-ng](https://github.com/perint/log.io-ng), if you'd like to help, please create an issue that you would like to become a contributor and I will add you :-)

hello Are you still maintaining this project?

**Comment by KenanSulayman** [comment]
No I'm not.
