### ISSUE TITLE
changing default green color

### ISSUE THREAD

**Issue by Geo-Joy** [NarrativeScience/log.io#155]
is there any way to change the defaut green color to any other.

I use log4js so can i get those color shown up here.

**Comment by lhillah** [comment]
Hi, 

I would like the color to be adapted to the type of log message, e.g. red when there is an error message, orange when there is a warning message. 

Best regards

**Comment by donniegallardo** [comment]
Tried playing with it today and added some additional search filters. I'm interested with for example with 500 errors or 404 status code.

I may pull request to add this if someone finds it useful.

![linematchescoloring](https://cloud.githubusercontent.com/assets/19543361/19269636/019b8392-8fbc-11e6-84c5-2ddd022fbd22.png)

**Comment by msmathers** [comment]
You can modify the SASS file in `ui/src/components/screens` and manually rebuild log.io, or you can use a custom chrome skin.
