### ISSUE TITLE
Support for file pattern matching in ?

### ISSUE THREAD

**Issue by lubos-bistak** [NarrativeScience/log.io#162]
Hello,

is there any support  in`harverster.conf` for matching multiple files by some pattern like `/var/log/some-app/some-app*.log`?

Lubos

**Comment by zoell** [comment]
+1

**Comment by federicot** [comment]
As a workaround you can do something like this in your harvester.conf:

```
var fs = require('fs');

log_files = fs.readdirSync('/var/log/apache2/');
for (var i=0; i<log_files.length; i++) {
  log_files[i] = '/var/log/apache2/'+log_files[i];
}

exports.config = {
  nodeName: "application_server",
  logStreams: {
    apache: log_files
  },
  server: {
    host: '0.0.0.0',
    port: 28777
  }
}
```

**Comment by colin-han** [comment]
@federicot your solution is a workaround, but it is a static file list. I want log.io can watch new files (which are created after harvester started) match the pattern.

**Comment by Denusdv** [comment]
I saw this question is pretty old, although there is not clear answer is such capability is supported.
I have the same scenario, the logs files are created dynamically for different processing with different prefix. I would like to watch them after the harvester started. Is it possible? thanks

**Comment by msmathers** [comment]
https://github.com/NarrativeScience/log.io/issues/211

**Comment by msmathers** [comment]
Support for globs and new file detection have been added in v0.4.14 https://github.com/NarrativeScience/log.io/releases/tag/v0.4.14
