### ISSUE TITLE
fail install with npm on os x

### ISSUE THREAD

**Issue by Gohan** [NarrativeScience/log.io#166]
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.

**Comment by jmdiego** [comment]
Anything on this??

**Comment by black1987** [comment]
Same problem here , i think it's related to the latest version of nodeJS

**Comment by msmathers** [comment]
v0.4.3 is a full rewrite that uses node.js 12, so this issue should be resolved.
