### ISSUE TITLE
I guess that log.io-ng is the best place to go now?

### ISSUE THREAD

**Issue by eashman** [NarrativeScience/log.io#167]
This is a great project but without active management, it seems like there are forks galore with fixes that are not getting merged or consolidated?

Is this fork the best one to go to?  If so, can those who have outstanding pull requests make sure they get put into that new repo?

https://github.com/perint/log.io-ng

Is where it was noted below is a somewhat up-to-date fork.

**Comment by OhadR** [comment]
+1

**Comment by hanneshal** [comment]
Hey @eashman,

good point. We wan't to rewrite log io to a new base and move from coffee script to plain JS (ES6).
So PR to log.io-ng are welcome, but we plan to rewrite it from ground up.  
No timeline yet, at the moment we try to organize this along our daily work ;) 

regards
Johannes

**Comment by COLABORATI** [comment]
haha, great, now there are two repos with this dead project.

**Comment by msmathers** [comment]
https://github.com/NarrativeScience/log.io/releases/tag/v0.4.3
