### ISSUE TITLE
Compilation fail with the source code

### ISSUE THREAD

**Issue by Neron-Liu** [NarrativeScience/log.io#171]
Hi,

I got a compile fail on my environment. Is there any required library that I missed? 

Thanks for help!
# 

neron@Atenza:~/Log.io/Log.io-master$ cake build
Generating src/templates.coffee from templates/_.html
Compiling src/_.coffee to lib/_.js
Compiling src/less/_ to lib/log.io.css
Browserifying src/client.coffee to lib/log.io.js
/home/neron/Log.io/Log.io-master/Cakefile:59
        throw err;
              ^
Error: Command failed: /bin/sh -c /usr/bin/env lessc /home/neron/Log.io/Log.io-master/src/less/log.io.less -compress -o /home/neron/Log.io/Log.io-master/lib/log.io.css
Unable to interpret argument o - if it is a plugin (less-plugin-o), make sure that it is installed under or at the same level as less
The compress option has been deprecated. We recommend you use a dedicated css minifier, for instance see less-plugin-clean-css.

  at ChildProcess.exithandler (child_process.js:751:12)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by SebastianOsuna** [comment]
+1

**Comment by naimpl** [comment]
Gents, -o is deprecated. 

In new lessc syntax you don't have to add -o to spcecify the output filename. just speciffy it without -o and it'll work

**Comment by msmathers** [comment]
v0.4.3 is a full rewrite that uses babel & SASS, so this specific issue should be addressed.
