### ISSUE TITLE
Fail in load home at linux

### ISSUE THREAD

**Issue by next-josemanuelrincon** [NarrativeScience/log.io#175]
When launch log.io-harvester with other non root user or supervisor, dont load correctly home

I have changed this in bin/log.io-harvester

+osenv=require('osenv')
-homeDir = process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
+homeDir=osenv.home()

This changes, fixed the problem above

**Comment by msmathers** [comment]
v0.4.3 no longer requires root/sudo to install, so that should address this issue.
