### ISSUE TITLE
set latest log that my app created along the time

### ISSUE THREAD

**Issue by yidaxia** [NarrativeScience/log.io#177]
My app creates a log every hours in the directory "/path/to/myapp.log".The name of the lastest log is changing as date like "2016-05-05-18".How to set the latest log file in config of log.io?

**Comment by msmathers** [comment]
https://github.com/NarrativeScience/log.io/issues/211

**Comment by msmathers** [comment]
Support for globs and new file detection have been added in v0.4.14 https://github.com/NarrativeScience/log.io/releases/tag/v0.4.14
