### ISSUE TITLE
Client/browser side logging only?

### ISSUE THREAD

**Issue by ghost** [NarrativeScience/log.io#178]
I love log.io and have used it in the past with Node. I understand that log.io harvests log files on the server to be able to present the messages in the browser. I also understand how to use the API to send messages directly for display in the browser without a source log file.

Is it possible or easy enough to embed log.io as a dependency of my client-side project and log directly from the browser? I'm basically looking for something nicer than FireBug.

**Comment by philmaker1** [comment]
Anyone know of a nice browser-based console besides firebug? I haven't looked into logging directly to log.io from inside the browser but does anyone think it'll be a big task?

**Comment by msmathers** [comment]
log.io has no plans to support receiving log messages from the browser... However, given that it already uses a bidirectional websocket to send messages to the browser, it would be pretty easy to modify the server code to accept log message events.
