### ISSUE TITLE
log.io-harvester load whole file

### ISSUE THREAD

**Issue by ghost** [NarrativeScience/log.io#179]
Is it possible to read whole content of the log file attached to harverster on application startup?

I've added few logs but somehow the app was killed and now i have only current history but the log is a lot bigger. Is there a way to force harvester to parse whole log file?

**Comment by Jonn3y** [comment]
Doesn't look like log.io is under active development anymore  ...

**Comment by msmathers** [comment]
log.io is only concerned with real-time message data, and has no plans to support persistence/history. Since it is designed to support multiple input types other than files, we can't guarantee that all input types will have access to historic data.
