### ISSUE TITLE
Use parameters in config log file

### ISSUE THREAD

**Issue by lucabecchetti** [NarrativeScience/log.io#183]
Hi, i need to set a file log with this format:

/var/www/html/api/storage/logs/laravel-$(date +%Y-%m-%d).log

how can i use parameters in file?

Thanks!

**Comment by msmathers** [comment]
There's a planned feature to support pattern matching in file path definitions (https://github.com/NarrativeScience/log.io/issues/211), however since v0.4 uses JSON configuration it won't be possible to run custom logic.

**Comment by msmathers** [comment]
Support for globs and new file detection have been added in v0.4.14 https://github.com/NarrativeScience/log.io/releases/tag/v0.4.14
