### ISSUE TITLE
Page does not load Past txt

### ISSUE THREAD

**Issue by MokeyII** [NarrativeScience/log.io#187]
This is more of a question than an issue.

How do you get it to load the whole text file rather than JUST new entries in the text file.

**Comment by audrummer15** [comment]
I think I would like to see this as a feature. Or at least configurable to load the last 'X' lines from all log files it' finds.

**Comment by MokeyII** [comment]
I agree with @audrummer15

**Comment by msmathers** [comment]
log.io is only concerned with real-time message data, and has no plans to support persistence/history. Since it is designed to support multiple input types other than files, we can't guarantee that all input types will have access to historic data.
