### ISSUE TITLE
My logs get rotated with a date/timestamp

### ISSUE THREAD

**Issue by ghost** [NarrativeScience/log.io#188]
Out of interest, is it possible to tell log.io to show me all logs under a directory? 

i.e. Something like "/usr/openv/netbackup/RestoreLogs/*"

**Comment by ren-kun** [comment]
Not to sure either. I can't even get log.io to run

**Comment by msmathers** [comment]
We've added a planned feature issue to support pattern matching in file paths: https://github.com/NarrativeScience/log.io/issues/211

**Comment by msmathers** [comment]
Support for globs and new file detection have been added in v0.4.14 https://github.com/NarrativeScience/log.io/releases/tag/v0.4.14
