### ISSUE TITLE
Errors installing on Raspberry Pi

### ISSUE THREAD

**Issue by scargill** [NarrativeScience/log.io#190]
Raspberry Pi - latest version, up to date - has Node-Red etc all up to date. Tried to install and..

Last login: Thu Apr 20 10:34:42 2017 from 192.168.1.32
pi@myboard:~ $ sudo npm install -g log.io --user "pi"
npm WARN deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.
/usr/bin/log.io-server -> /usr/lib/node_modules/log.io/bin/log.io-server
/usr/bin/log.io-harvester -> /usr/lib/node_modules/log.io/bin/log.io-harvester

> contextify@0.1.15 install /usr/lib/node_modules/log.io/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.10.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/log.io/node_modules/contextify/.node-gyp"
make: Entering directory '/usr/lib/node_modules/log.io/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /usr/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.10.2/include/node/v8.h:3275): Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
../src/contextify.cc:151:72: warning: ‘void v8::ObjectTemplate::SetAccessCheckCallbacks(v8::NamedSecurityCallback, v8::IndexedSecurityCallback, v8::Local<v8::Value>)’ is deprecated (declared at /usr/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.10.2/include/node/v8.h:4802): Use SetAccessCheckCallback instead [-Wdeprecated-declarations]
                                        GlobalPropertyIndexedAccessCheck);
                                                                        ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated (declared at /usr/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.10.2/include/node/v8.h:2922): Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated (declared at /usr/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.10.2/include/node/v8.h:2922): Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated (declared at /usr/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.10.2/include/node/v8.h:2922): Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  COPY Release/contextify.node
make: Leaving directory '/usr/lib/node_modules/log.io/node_modules/contextify/build'

> ws@0.4.32 install /usr/lib/node_modules/log.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/lib/node_modules/log.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:94: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/lib/node_modules/log.io/node_modules/ws/build'

> log.io@0.3.4 postinstall /usr/lib/node_modules/log.io
> cake ensure:configuration

Creating ~/.log.io/ for configuration files.
If this fails, run npm using a specific user: npm install -g log.io --user 'ubuntu'
fs.js:923
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/root/.log.io/'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.action (/usr/lib/node_modules/log.io/Cakefile:79:10)
    at invoke (/usr/lib/node_modules/log.io/node_modules/coffee-script/lib/coffee-script/cake.js:44:26)
    at Object.exports.run (/usr/lib/node_modules/log.io/node_modules/coffee-script/lib/coffee-script/cake.js:69:21)
    at Object.<anonymous> (/usr/lib/node_modules/log.io/node_modules/coffee-script/bin/cake:7:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! log.io@0.3.4 postinstall: `cake ensure:configuration`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the log.io@0.3.4 postinstall script 'cake ensure:configuration'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the log.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cake ensure:configuration
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs log.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls log.io
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-04-24T23_32_33_435Z-debug.log
pi@myboard:~ $

**Comment by lasrie** [comment]
Hi,
I had similar problems, which I managed to solve, came across your thread and wanted to help the next person coming.
Your error `Error: EACCES: permission denied, mkdir '/root/.log.io/'` seems to indicate permissioning problems, what fixed that for me was installing node using the nvm
(see: https://github.com/creationix/nvm/blob/master/README.md#install-script)

log.io seems to not be maintained very well and was not working with the current node version for me. When I used node version 6 it was working for me;

`nvm install 6
nvm alias default 6`

Hope you get it running for yourself :)

**Comment by msmathers** [comment]
v0.4.3 uses "bin" scripts in `package.json` to run the process as the current user, and uses the current user's home directory for configuration.  Hopefully that will resolve this specific issue.
