### ISSUE TITLE
Amount of logs.

### ISSUE THREAD

**Issue by guilhermebasalia** [NarrativeScience/log.io#195]
I would like to know what is the amount of log per second that the tool can handle analyze and send?

**Comment by msmathers** [comment]
v0.4.3 has a completely rewritten web UI using React 16, so the performance characteristics have changed.  The main bottleneck we've observed is the DOM manipulation / painting process in the browser.  The TCP/socket.io communication is extremely lightweight and can handle large throughput.

We don't have any hard benchmarks, but have observed the tool handling 100 messages per second when running locally.
