### ISSUE TITLE
Can we pass "logStreams" as CLI parameter in harvester.conf ?

### ISSUE THREAD

**Issue by nainav** [NarrativeScience/log.io#196]
Hi , 

I have a question regarding a use case !

-  Monitoring different files which are not present in harvester.conf

- Can we pass "logStreams" as CLI parameter in harvester.conf ?

**Comment by msmathers** [comment]
v0.4.3 uses JSON configuration.  You can have a separate process dynamically generate a JSON file, then use the `LOGIO_FILE_INPUT_CONFIG_PATH` environment variable to point at your configuration file.
