### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by victorsndvg** [NarrativeScience/log.io#197]
Hi all, 

I'm quite new here, but, as a starting point, I would like to get some info about the REST API.

Is there a link were to learn how to use the API?

I would like to create/destroy streams, nodes and send messages to them using curl or an small python app.

Someone can help me?

Really appreciate you help!

**Comment by victorsndvg** [comment]
Ok, messages are send using TCP protocol. I'm trying to use an small python to send TCP messages described on README but it doesn't work. Any quick tip?

**Comment by msmathers** [comment]
The TCP message interface is documented in the README.  See the file input code as an example of creating a TCP socket and writing messages to it: https://github.com/NarrativeScience/log.io/blob/master/inputs/file/src/input.ts
