### ISSUE TITLE
 cake ensure:configuration

### ISSUE THREAD

**Issue by hihuazi** [NarrativeScience/log.io#198]
cake ensure:configuration
npm ERR! You can get their info via:
npm ERR!     npm owner ls log.io
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.10.0-693.2.2.el7.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "log.io"
npm ERR! cwd /root
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by timosir** [comment]
先降低node 的版本，安装完成后，在升级node 的版本，即可

**Comment by msmathers** [comment]
v0.4.3 uses node 12 and babel for all builds, so this issue should no longer exist.
