### ISSUE TITLE
Bug when try to read log on network drive

### ISSUE THREAD

**Issue by azertyii** [NarrativeScience/log.io#199]
Hello,
I'm on ubuntu 16.04. When i read a log file dpkg.log on my own virtual machine it works. But when i create a network drive to read a log file on another server it doesn't work.
There are my harvester "application_server" but no log in log.io.
My harvester.conf : 
exports.config = {
nodeName: "application_server",
logStreams:{
message:[
"/media/configuration/idsQueue.log"  //This is my log file
]
},
server: {
host '127.0.0.1',
port: 28777
}
}

Thx,

**Comment by jnovack** [comment]
This does not work with Node v8. This project was last alive in 2014.  You are advised to seek an alternate project.

**Comment by msmathers** [comment]
This issue is being caused by something below the application stack.  log.io uses node.js' native `fs.watch()` to detect file changes, which uses `inotify` on linux.  There's a known issue with inotify & NFS: https://stackoverflow.com/a/4231277
