### ISSUE TITLE
error install ubuntu bionic

### ISSUE THREAD

**Issue by lucabecchetti** [NarrativeScience/log.io#200]
make: Entering directory '/usr/local/lib/node_modules/log.io/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/becchettiluca/.node-gyp/8.10.0/include/node/v8.h:26:0,
                 from /home/becchettiluca/.node-gyp/8.10.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/becchettiluca/.node-gyp/8.10.0/include/node/v8.h:3851:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/becchettiluca/.node-gyp/8.10.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’; did you mean ‘SetAccessCheckCallback’?
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^~~~~~~~~~~~~~~~~~~~~~~
                SetAccessCheckCallback

**Comment by maxlein** [comment]
Same for me....

**Comment by jnovack** [comment]
This does not work with Node v8. This project was last alive in 2014.  You are advised to seek an alternate project.

**Comment by thinkMX** [comment]
I'm using node v10. Too sad

**Comment by msmathers** [comment]
v0.4.3 uses node 12, so that should address most OS compatibility issues.
