### ISSUE TITLE
error while installing in linux 16.04

### ISSUE THREAD

**Issue by vipulpandeykv** [NarrativeScience/Log.io#201]
sudo npm install -g log.io --user "root"
npm WARN deprecated coffee-script@1.4.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.
npm WARN deprecated connect@2.7.2: connect 2.x series is deprecated
/usr/bin/log.io-server -> /usr/lib/node_modules/log.io/bin/log.io-server
/usr/bin/log.io-harvester -> /usr/lib/node_modules/log.io/bin/log.io-harvester

> contextify@0.1.15 install /usr/lib/node_modules/log.io/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/log.io/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:26:0,
                 from /home/vipulpandey/.node-gyp/8.12.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:3901:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:26:0,
                 from /home/vipulpandey/.node-gyp/8.12.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:3454:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:26:0,
                 from /home/vipulpandey/.node-gyp/8.12.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:3454:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:26:0,
                 from /home/vipulpandey/.node-gyp/8.12.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8.h:3454:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/vipulpandey/.node-gyp/8.12.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
contextify.target.mk:101: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/usr/lib/node_modules/log.io/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/log.io/node_modules/contextify
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by roysG** [comment]
any update?
