### ISSUE TITLE
Mask Log Data

### ISSUE THREAD

**Issue by astutesoftware** [NarrativeScience/log.io#202]
What would be an ideal approach that a log that is being streamed has a middle layer or mechanism to mask some of the sensitive data.
I have a use case where support personnel need to track logs looking for sms delivery to a particular recipient by phone number but the log contains more than required sensitive data.
Ideally this case would require a middleware which can reside at the server end and masks the data before streaming or be embedded at the client end (browser)
any thoughts?

**Comment by msmathers** [comment]
There are currently no plans for middleware support... I'd recommend writing a separate process that reads the raw log files with sensitive data and outputs new, sanitized log files.  Then point log.io at the sanitized files.
