### ISSUE TITLE
Browser slow-down/freezes.

### ISSUE THREAD

**Issue by dailytabs** [NarrativeScience/log.io#204]
log.io has always been slow and laggy, but today's experience was by far the worst I have ever had.

The site had been up for over an hour. I had filtered and cleared the filter. I scrolled around a bit. Then, it sat there for a while. When I came back to it:
1. I clicked New Screen button.
2. Nothing happened.
3. I clicked New Screen button.
4. Nothing happened.
5. I opened Firefox dev tools.
6. The dev tools opened after a bit and log.io updated to show 3 screens.
7. I closed the dev tools.
8. Over 15 minutes later, the screen has not updated to re-take the space occupied by the dev tools. (See screenshot.)
9. Additionally, the interface is completely unresponsive. I cannot scroll or click anything. Sometimes the cursor will change to indicate I can click, but nothing happens when I do so.
10. After the 15 minutes, I closed the tab.

![log io](https://user-images.githubusercontent.com/1219653/55831532-4f888800-5ae1-11e9-9e5b-ef8114596a49.png)

**Comment by msmathers** [comment]
v0.4.3 has a completely rewritten web UI using React 16, so this specific issue no longer exists.  Please report any new UI performance issues as you notice them, thanks!
