### ISSUE TITLE
why install log.io failed

### ISSUE THREAD

**Issue by xulayen** [NarrativeScience/log.io#208]
![image](https://user-images.githubusercontent.com/15044564/66726061-b9576500-ee69-11e9-8e9a-6c2c48ca5f04.png)

**Comment by xulayen** [comment]
![image](https://user-images.githubusercontent.com/15044564/66726248-ccb70000-ee6a-11e9-81d7-1dcea7deb778.png)

**Comment by xulayen** [comment]
![image](https://user-images.githubusercontent.com/15044564/66726282-fa03ae00-ee6a-11e9-8993-cc18ec48ab7b.png)

**Comment by TerribleLife** [comment]
搞定了吗兄弟？我也装不起来

**Comment by jamesborkowski** [comment]
I get the same failure on the latest version of Ubuntu

**Comment by TerribleLife** [comment]
> I get the same failure on the latest version of Ubuntu

I don't think it is related to the verison of Ubuntu. Try some other version of node. I changed my node version to 6.17.1 then successfully installed.

**Comment by msmathers** [comment]
v0.4.3 uses node 12+ and should work on most modern OSes.
