### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by adriaand007** [NarrativeScience/log.io#216]
Hi
Would it be posible to enable a filter section 
Like the older version
![image](https://user-images.githubusercontent.com/13329360/72969069-75abba00-3dcd-11ea-991f-bfe81697fc68.png)
Also , maybe a button to load older log entries in the logfile ...

**Comment by crackfoo** [comment]
Yes, I'm curious where this filter is now....

**Comment by babarnazmi** [comment]
It's a must have, filter + freeze functions were very useful, plus basic http authentication
+1

**Comment by harlanc** [comment]
why this is removed

**Comment by msmathers** [comment]
Added filter input in v0.4.12

**Comment by msmathers** [comment]
See #229

**Comment by harlanc** [comment]
@msmathers  how to update using the  nom command? thank you.

npm install -g log.io
