### ISSUE TITLE
 How to write configuration file when monitoring many log files 

### ISSUE THREAD

**Issue by 592713711** [NarrativeScience/log.io#219]
for example:
I have 100 log files (xx.log) all have .log suffix，
How can I not configure them one by one to ~/.log.io/inputs/file.json

**Comment by msmathers** [comment]
You can specify a directory path in configuration and it will watch all files in that directory when the process starts up. However it will not pick up files nested in descendant directories, nor will it discover new files to watch after the process has started.

#211 will allow support for wildcard patterns, and will explore new file discovery.

**Comment by 592713711** [comment]
thx ~
this help for me
