### ISSUE TITLE
Logs not updating

### ISSUE THREAD

**Issue by rishabh9988** [NarrativeScience/log.io#224]
While changing the file logs are not updating on the port only previous first changes are shown their

**Comment by msmathers** [comment]
I'm not sure I understand.  You're seeing some logs messages appear in the browser and then they all abruptly stop?

**Comment by rishabh9988** [comment]
While setting up only the changes made initially in the file are shown in the logs. Then if any change made in the file logs,file logs are not updating.

**Comment by msmathers** [comment]
So are you going back and modifying existing lines in the log file that have already been sent to the server?  If so, that situation is not supported by log.io.  It assumes all log lines written to a file are immutable.

**Comment by msmathers** [comment]
I'm going to close this issue unless we're given steps to reproduce this behavior.
