### ISSUE TITLE
无配置文件

### ISSUE THREAD

**Issue by xinsir88** [NarrativeScience/log.io#236]
新安装的log.io在宿主目录下，并没有找到配置文件，这个文件是需要自己创建嘛？
`ubuntu@ip-172-30-5-72:~$ sudo npm install -g log.io
/usr/local/bin/log.io-server -> /usr/local/lib/node_modules/log.io/bin/log.io-server
+ log.io@0.4.15
updated 1 package in 1.943s
ubuntu@ip-172-30-5-72:~$ pwd
/home/ubuntu
ubuntu@ip-172-30-5-72:~$ ls -a ~/
.  ..  .bash_history  .bash_logout  .bashrc  .cache  .config  .npm  .profile  .ssh  .sudo_as_admin_successful
ubuntu@ip-172-30-5-72:~$ ll -a ~/
total 40
drwxr-xr-x 6 ubuntu ubuntu 4096 May  6 07:50 ./
drwxr-xr-x 3 root   root   4096 May  6 06:05 ../
-rw------- 1 ubuntu ubuntu  459 May  6 07:44 .bash_history
-rw-r--r-- 1 ubuntu ubuntu  220 Feb 25 12:03 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu 3771 Feb 25 12:03 .bashrc
drwx------ 2 ubuntu ubuntu 4096 May  6 06:09 .cache/
drwx------ 3 ubuntu ubuntu 4096 May  6 07:50 .config/
drwxrwxr-x 4 ubuntu ubuntu 4096 May  6 07:50 .npm/
-rw-r--r-- 1 ubuntu ubuntu  807 Feb 25 12:03 .profile
drwx------ 2 ubuntu ubuntu 4096 May  6 06:05 .ssh/
-rw-r--r-- 1 ubuntu ubuntu    0 May  6 06:09 .sudo_as_admin_successful`

**Comment by msmathers** [comment]
> The newly installed log.io does not find a configuration file in the host directory. Should I create this file myself?

Correct, you will need to manually create configuration files. The `log.io` package doesn't require you to create a configuration file, however if you want to use custom ports for the servers, you can specify them in `~/.log.io/server.json`.

For the `log.io-file-input` package, specify which log files to watch in `~/.log.io/inputs/file.json`.

See the README for configuration examples for both packages.
