### ISSUE TITLE
Handle changing log file names

### ISSUE THREAD

**Issue by spier** [NarrativeScience/log.io#24]
If the name of a log file is changing frequently (e.g. daily), is there a way to still harvest such files?
Log.io doesn't seem to like symlinks.

**Comment by msmathers** [comment]
This is a duplicate of #211, closing

**Comment by msmathers** [comment]
Support for globs and new file detection have been added in v0.4.14 https://github.com/NarrativeScience/log.io/releases/tag/v0.4.14
