### ISSUE TITLE
IE 9 gets blank screen

### ISSUE THREAD

**Issue by lbrigman124** [NarrativeScience/log.io#25]
When log.io is configured on a machine pointing IE 9 browser at it get only the bottom info from the page.
Just the +stream +history buttons (grayed out) and the updates status section.  No harvesters to configure, no stream windows
and no history windows.

This is probably has to do with jquery 1.4.2 but that is just a guess.

**Comment by msmathers** [comment]
Log.io v0.4.x has been completely rewritten using React/SASS and should be compatible with all modern browsers.
