### ISSUE TITLE
log.io on Ubuntu20

### ISSUE THREAD

**Issue by pdasgupt** [NarrativeScience/log.io#253]
log.io installs successfully. However, there is no .log.io directory. Even if I create a directory and put in a file.json file I get the following error with log.io-file-input

./log.io-file-input 

ERROR: Unable to find a configuration file.

Create a configuration file at ~/.log.io/inputs/file.json,
or specify a custom path via an environment variable: LOGIO_FILE_INPUT_CONFIG_PATH.

See README for configuration examples.

**Comment by msmathers** [comment]
Did you create a configuration file in `~/.log.io/inputs/file.json`? (Note the `inputs` directory).

I'll plan to update the server & harvester installer to create empty configuration files in the appropriate paths.

**Comment by pdasgupt** [comment]
Yes I did but it did not work. I had it working on Ubuntu18 before.

**Comment by pdasgupt** [comment]
Got it working. Thanks

**Comment by LinuxforPunks** [comment]
But **how** did you get this working? I have come into the same error today on Raspbian 12.
