### ISSUE TITLE
List of nodes and streams in web client becomes corrupted (0.3.0)

### ISSUE THREAD

**Issue by jochenonline** [NarrativeScience/log.io#52]
I have five machines running. One with the `log.io-server` and a `log.io-harvester`, four only with  a `log.io-harvester`.

When I start the server and afterwards the five harvesters everything looks fine. But after a while (some minutes). The names of the streams and nodes start becoming corrupted:
- empty list elements appear
- names are cut (i. e. "ar0037002" becomes "ar0", "mongodb" becomes "mo")
- some nodes or streams disappear completely 

With time going on things get worse. 

Refreshing the browser window does not help. I have to restart the server and sometimes also the harvesters.

Bug, feature or me?

**Comment by geek-kb** [comment]
I'm on 0.3.4 and the problem exists.. any idea how to fix it?
