### ISSUE TITLE
Configuration options docs

### ISSUE THREAD

**Issue by jamengual** [NarrativeScience/log.io#64]
Hi Guys.

I finally got my log.io server working but I was looking for more detailed documentation about the configuration options for the web_server, harvester like to enable simple auth, limit  networks and such.

I found this :
http://askubuntu.com/questions/170061/how-to-install-log-io but looks outdated.

is there such a document ?

Thanks.

**Comment by sharan01** [comment]
> The provided sample configuration files expose all available configuration options for all log.io components:
> 
> https://github.com/NarrativeScience/Log.io/tree/master/conf
@msmathers 
unable to find configurations options for adding basic auth
