### ISSUE TITLE
First character of log string showed as single line (sometimes multiple)

### ISSUE THREAD

**Issue by jochenonline** [NarrativeScience/log.io#66]
Sometimes before a log line is displayed the first character of the line is presented as a single line. This looks like this then:

```
release linux [
release linux [
release linux [4] 2013-04-11 13:54:17 [INFO] 6960 0 6960
release linux [4] 2013-04-11 13:54:54 [INFO] [2013-04-11 13:54:54] [192.168.0.10]
```

`release` and `linux` are stream and node. The log string begins with `[`.

**Comment by wilpey** [comment]
I have the same issue. Anyone managed to solve this?

**Comment by msmathers** [comment]
log.io v0.4.x has been completely rewritten and has new message parsing logic that should address this... please open a new ticket if this behavior continues, thanks!
