### ISSUE TITLE
Preserve whitespaces in messages

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [NarrativeScience/log.io#74]
I use log.io along with a project that uses pretty printing for objects/arrays in node.js. Log.io currently loses intents for these lines. To preserve them I would something like additional css property `white-space:pre` but this can prevent long lines from wrapping. Any ideas?

**Comment by msmathers** [comment]
v0.4x has a completely rewritten UI component, now messages are rendered with a `white-space: pre-wrap;` style, which should address your issue.
