### ISSUE TITLE
Custom config file location

### ISSUE THREAD

**Issue by maxekman** [NarrativeScience/log.io#75]
I would be nice to be able to define another config file with a flag for the harvester bin file. 

For example:

```
log.io-harvester -c <path to config file>
```

**Comment by mspinassi** [comment]
Sooo +1 on this.

**Comment by toksea** [comment]
+1

**Comment by msmathers** [comment]
This has been added in v0.4x, you can use the following environment variables to set config file location: `LOGIO_SERVER_CONFIG_PATH` and `LOGIO_FILE_INPUT_CONFIG_PATH`
