### ISSUE TITLE
SSL Delay

### ISSUE THREAD

**Issue by ddarbyson** [NarrativeScience/log.io#84]
When browsing via https:// there seems to an exact 10 second delay before any Streams or Nodes are listed. Anyone else experiencing this?

v0.3.3

**Comment by msmathers** [comment]
v0.4x doesn't natively support SSL, we now recommend using an nginx reverse proxy to add SSL termination, authentication, etc...  Use the following recipe for reverse proxying socket.io: https://stackoverflow.com/a/29232687
